# appの中で実行する
createiseed:
	# php artisan iseed books
	# php artisan iseed authors
	# php artisan iseed book_categories
	# php artisan iseed category_links
	# php artisan iseed category_primaries
	# php artisan iseed category_secondaries
	# php artisan iseed failed_jobs
	# php artisan iseed labels
	# php artisan iseed migrations
	# php artisan iseed users
	chown -Rh 1000:1000 ./database/seeds
	chmod -R 775 ./database/seeds
